spring:
    datasource:
        url: jdbc:postgresql://localhost5432/checkout
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-test-query: select 1
    jpa:
        hibernate:
            ddl-auto: create_drop
        properties:
            hibernate:
                default_schema: checkout
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: true
            use_sql_comments: true
            jdbc:
                lob:
                    non_contextual_creation: true

